# Generated by Django 5.0.7 on 2024-11-30 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_vendor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='video',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gallery',
            name='filename',
            field=models.CharField(max_length=300),
        ),
    ]
