# Generated by Django 5.0.7 on 2024-12-05 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_gallery_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weddingblog',
            name='VENDOR',
        ),
        migrations.AddField(
            model_name='weddingblog',
            name='LOGIN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.login'),
            preserve_default=False,
        ),
    ]
