# Generated by Django 5.0.7 on 2024-12-07 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_weddingblog_vendor_weddingblog_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='weddingblog',
            name='video',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
