# Generated by Django 5.0.7 on 2025-02-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_weddingblog_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='category',
            field=models.CharField(default='hahjj', max_length=100),
            preserve_default=False,
        ),
    ]
